{{- if and .Values.contextEngine.enabled .Values.persistence.contextEngineVault.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jca-worker.contextEngineName" . }}-vault
  labels:
    {{- include "jca-worker.labels" . | nindent 4 }}
    component: context-engine
spec:
  accessModes:
    - {{ .Values.persistence.contextEngineVault.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.contextEngineVault.size }}
  {{- if .Values.persistence.contextEngineVault.storageClassName }}
  storageClassName: {{ .Values.persistence.contextEngineVault.storageClassName }}
  {{- end }}
{{- end }}
