{{- if .Values.persistence.gateway.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jca-worker.gatewayName" . }}-data
  labels:
    {{- include "jca-worker.labels" . | nindent 4 }}
    component: gateway
spec:
  accessModes:
    - {{ .Values.persistence.gateway.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.gateway.size }}
  {{- if .Values.persistence.gateway.storageClassName }}
  storageClassName: {{ .Values.persistence.gateway.storageClassName }}
  {{- end }}
{{- end }}
